### ISSUE TITLE
Problems with changes to commit #3f0afe

### ISSUE THREAD

**Issue by ArashPartow** [moves-rwth/storm#1]
With regards to the commit https://github.com/moves-rwth/storm/commit/3f0afe952682dc810e7c0fc9a5be92c360d3c19e, I'm not sure why it was necessary as ExprTk already supports '_' and '. in symbol names.

More information can be found here: 
https://github.com/ArashPartow/exprtk/blob/master/readme.txt#L4055

-----

The change made in the commit will cause problems with expressions. As a simple example the following expression:  ".123" will result in two tokens which are a symbol: "." and a number: "123" neither of which is correct.

**Comment by cdehnert** [comment]
First of all, thanks for having a look at this!

You are right, this change was a bit crude and I did it in a hurry to get something specific working.

In general, we need our identifiers to be able to start with an underscore. This is currently not possible if my quick test does not fail me or am I mistaken here? If that's indeed an issue, what would be the best way to resolve it?

The dot-change, however, was really unnecessary.

**Comment by ArashPartow** [comment]
I see, so you were after variables with names like _x  _abc.123 etc...  my bad, I'll close this issue.

**Comment by cdehnert** [comment]
Is this a necessary restriction though or is it by choice? Or put differently: what prevents ExprTk from considering underscores as legal starting characters of identifiers?

Other than that: thanks for making ExprTk! It's pretty fast.

**Comment by ArashPartow** [comment]
@cdehnert it's more by choice, an attempt to make the expressions look more "orderly"...


------


> thanks for making ExprTk! It's pretty fast.

Thank-you! :D

**Comment by cdehnert** [comment]
I understand your incentive. In our input languages, we also don't have identifiers with leading underscores. However, sometimes we internally have to create temporary variables and to avoid name clashes we resort to prefix them with underscores.
