### ISSUE TITLE
Storm is compiled without Z3 Support

### ISSUE THREAD

**Issue by saxonshreyas** [moves-rwth/storm#105]
I am trying to build Storm from source for my Linux Machine. I am following the instructions posted on the Getting Started page. My `cmake` and `make` both ran successfully, however when I run my testing script I get the following error for all of the tests: 

```
unknown file: Failure
C++ exception with description "NotSupportedException: Storm is compiled without Z3 support." thrown in the test body.
[  FAILED  ] BeliefExplorationTest/5.simple_Rmin, where TypeParam = (anonymous namespace)::RefineDoubleVIEnvironment (1 ms)
[ RUN      ] BeliefExplorationTest/5.simple_slippery_Rmax
ERROR (Z3SmtSolver.cpp:118): Storm is compiled without Z3 support.
```

I am not sure what Z3 is exactly. I am running this on a university computer too so I am not exactly an admin for my computer. Any suggestions to fix this would be highly appreciated.

**Comment by volkm** [comment]
Z3 is an SMT library which we use to evaluate expressions. This is important for example when parsing Prism or Jani input and you need to have z3 present for nearly all tasks in Storm. Normally, you would install the corresponding Linux package `libz3-dev` on your Linux machine. The necessary commands for all required dependencies can be found in our [documentation](https://www.stormchecker.org/documentation/obtain-storm/dependencies.html#-debian-9-stretch-and-higher-and). The easiest way is to execute the commands and install all required dependencies automatically.

However, if you have no possibility to install packages, you need to build z3 for yourself, see the [z3 Github documentation](https://github.com/Z3Prover/z3#building-z3-using-make-and-gccclang).

Note that we also provide [virtual machine images](https://www.stormchecker.org/documentation/obtain-storm/vm.html) or [Docker containers](https://www.stormchecker.org/documentation/obtain-storm/docker.html).

If you encounter any problems, let me know.
