### ISSUE TITLE
GitHub Workflows

### ISSUE THREAD

**Issue by sjunges** [moves-rwth/storm#108]
When forking storm, one now gets a daily email with problems because things do require a specific setup of repos. 
Is it possible to fix e.g. deploying the documentation to this particular repo mirror? (Basically, saying it should only do this when on moves-rwth/storm?)

I have no clue how GitHub actions precisely works...

**Comment by volkm** [comment]
I modified the Github Actions (see PR #109) to skip steps on the forks which are only allowed on the main repo.

This however does not get rid of the notifications. Instead, I now got mails informing me that the action was skipped. The only solutions I see at the moment for you is to either completely disable the Github Actions on the fork or change the notification settings such that they are only sent for failed actions (see [here](https://docs.github.com/en/github/managing-subscriptions-and-notifications-on-github/configuring-notifications#github-actions-notification-options)).
