### ISSUE TITLE
Upgrade Sylvan Version

### ISSUE THREAD

**Issue by tquatmann** [moves-rwth/storm#138]
We should update the shipped sylvan version at some point to take advantage of recent improvements there. One particular thing is native ARM support which apparently does not work with the current version.
Also, as far as I could see, our current version also cannot be compiled with c++17.

As the [sylvan changelog](https://github.com/trolando/sylvan/blob/master/CHANGELOG.md) puts it, updating sylvan will break things, so this needs to be done with care. This might also be relevant for PR #122 (although this issue should not prevent us from merging the PR, I think)

**Update**: @dbasgoeze is working on this.

**Comment by sjunges** [comment]
https://github.com/moves-rwth/storm/pull/273 fixes this issue.
