### ISSUE TITLE
brew install error

### ISSUE THREAD

**Issue by LebronX** [moves-rwth/storm#140]
Hi,

I follow this link to brew install storm. When I run `brew install stormchecker`, it reports error:
`curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "ginac"
Download failed: https://www.ginac.de/ginac-1.8.0.tar.bz2`

Thanks

**Comment by tquatmann** [comment]
The issue is related to the installation of Ginac (a dependency of Storm). The Ginac version has changed to `1.8.1` three days ago. Please try the following:

```
brew update
brew install ginac
```

If this runs through without errors, you can retry the installation of Storm. If not, please let us know.

**Comment by LebronX** [comment]
Thanks! It works now.
