### ISSUE TITLE
Monotonicity analysis - Dot file generation

### ISSUE THREAD

**Issue by Sara-Iftikhar** [moves-rwth/storm#147]
I have a DTMC model. I want to do monotonicity analysis of my model and want to generate the dot output file. By following this [link](https://www.stormchecker.org/documentation/usage/running-storm-on-parametric-models.html), I am using the cammand; 

`$ storm-pars --prism model.prism --monotonicity-analysis --bisimulation --mon:dotOutput`

But I am unable to find the resultant file anywhere in my path, even if I provide the file name.

Please correct me if I am making a mistake in the command.

**Comment by jipspel** [comment]
Thanks for your question!
In your command the property and region are missing. The property is needed to compute the =) and =( states, the region is needed to check for the monotonicity.
See also this [link](https://www.stormchecker.org/documentation/usage/running-storm-on-parametric-models.html#example-3-checking-the-monotonicity-of-a-parameter)

**Comment by sjunges** [comment]
I assume that this issue has been solved. If not, feel free to reopen.
