### ISSUE TITLE
Latest version of Spot requires c++17

### ISSUE THREAD

**Issue by sjunges** [moves-rwth/storm#181]
Using the latest version of spot, e.g. the one you get standard via brew requires c++17. We should decide how to support this? Shall we set C++17 on recent compilers  and disable using spot on old ones?

**Comment by tquatmann** [comment]
Yes, we can check the installed Spot version like this
```
        if("${SPOT_VERSION}" VERSION_LESS "2.10.0")
        	message(STATUS "Storm - Using system version of Spot ${SPOT_VERSION} (include: ${SPOT_INCLUDE_DIR}, library: ${SPOT_LIBRARIES}).")
        	set(STORM_HAVE_SPOT ON)
		else()
			message( WARNING "Storm - System version of Spot ${SPOT_VERSION} is incompatible with this version of Storm. To use spot, consider updating your Storm version or setting cmake options STORM_USE_SPOT_SYSTEM=OFF and STORM_USE_SPOT_SHIPPED=ON." )
		endif()
```
Once we moved to C++17 (which we really should do directly after releasing), everything should work again.

**Comment by sjunges** [comment]
Thanks for the fix. I think we should keep this version open.
