### ISSUE TITLE
Installation via brew fails on OSX 10.13.4

### ISSUE THREAD

**Issue by merkste** [moves-rwth/storm#19]
I have troubles to install storm via homebrew. To set up a clean environment, I create a dedicated user account and removed macports temporarily. It seems to be related to Carl (, again). Do you need further information to debug that issue?

    homebrew$ brew install stormchecker
    ==> Installing stormchecker from moves-rwth/storm
    ==> Installing dependencies for moves-rwth/storm/stormchecker: moves-rwth/misc/carl
    ==> Installing moves-rwth/storm/stormchecker dependency: moves-rwth/misc/carl
    ==> Downloading https://github.com/smtrat/carl/archive/17.12.zip
    Already downloaded: /Users/homebrew/Library/Caches/Homebrew/carl-17.12.zip
    ==> cmake /private/tmp/carl-20180418-75318-588i2n/carl-17.12 -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/Users/homebrew/bin/homebrew/
    ==> make install
    Last 15 lines from /Users/homebrew/Library/Logs/Homebrew/carl/02.make:
    [ 50%] Built target gtest
    Scanning dependencies of target gtest_main
    [ 75%] Building CXX object googlemock/gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
    [100%] Linking CXX static library libgtest_main.a
    [100%] Built target gtest_main
    cd /tmp/carl-20180418-75318-e97jjv/resources/src/GTest-EP-build && 
    /Users/homebrew/bin/homebrew/Cellar/cmake/3.11.1/bin/cmake -E touch /tmp/carl-20180418-75318-e97jjv/resources/src/GTest-EP-stamp/GTest-EP-build
    [  8%] No install step for 'GTest-EP'
    cd /tmp/carl-20180418-75318-e97jjv/resources/src/GTest-EP-build && 
    /Users/homebrew/bin/homebrew/Cellar/cmake/3.11.1/bin/cmake -E echo_append
    cd /tmp/carl-20180418-75318-e97jjv/resources/src/GTest-EP-build && 
    /Users/homebrew/bin/homebrew/Cellar/cmake/3.11.1/bin/cmake -E touch /tmp/carl-20180418-75318-e97jjv/resources/src/GTest-EP-stamp/GTest-EP-install
    [  8%] Completed 'GTest-EP'
    /Users/homebrew/bin/homebrew/Cellar/cmake/3.11.1/bin/cmake -E make_directory /tmp/carl-20180418-75318-e97jjv/CMakeFiles
    /Users/homebrew/bin/homebrew/Cellar/cmake/3.11.1/bin/cmake -E touch /tmp/carl-20180418-75318-e97jjv/CMakeFiles/GTest-EP-complete
    /Users/homebrew/bin/homebrew/Cellar/cmake/3.11.1/bin/cmake -E touch /tmp/carl-20180418-75318-e97jjv/resources/src/GTest-EP-stamp/GTest-EP-done
    [  8%] Built target GTest-EP
    make: *** [all] Error 2
    
    If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
    https://github.com/moves-rwth/homebrew-misc/issues

**Comment by cdehnert** [comment]
The output of

brew install stormchecker -vd 

couldn't hurt. In the meantime, I try reproducing the issue on my machine. In any case, you might want to install the current master branch version if you want a version that fixes issue #18. In that case, you might want to 

brew install stormchecker --HEAD -vd

**Comment by cdehnert** [comment]
For me, `brew install stormchecker --HEAD` works flawlessly, so I am a bit dependent on your debug output to resolve the issue.

**Comment by merkste** [comment]
Doing `brew install stormchecker --HEAD -vd` yields the following debug output: [install_storm.log](https://github.com/moves-rwth/storm/files/1923937/install_storm.log)

**Comment by cdehnert** [comment]
According to the log, your machine can't execute aclocal:

```
Can't exec "aclocal": No such file or directory at /Users/homebrew/bin/homebrew/Cellar/autoconf/2.69/share/autoconf/Autom4te/FileUtils.pm line 326.
```

I'm not exactly sure whether why this happens on your machine, because we depend on the brew package `automake` which provides `aclocal`. Can you check whether `automake` is installed via

```
brew info automake
```

and if so, whether you can invoke `aclocal`?

**Comment by merkste** [comment]
I got the following:

    homebrew$ brew info automake
    automake: stable 1.16.1 (bottled)
    Tool for generating GNU Standards-compliant Makefiles
    https://www.gnu.org/software/automake/
    /Users/homebrew/bin/homebrew/Cellar/automake/1.16.1 (131 files, 3MB) *
      Poured from bottle on 2018-04-18 at 11:39:54
    From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/automake.rb
    ==> Dependencies
    Required: autoconf ✔
    homebrew$ which automake
    /Users/homebrew/bin/homebrew/bin/automake
    homebrew$ aclocal
    aclocal: error: 'configure.ac' is required
    homebrew$ which aclocal
    /Users/homebrew/bin/homebrew/bin/aclocal

**Comment by cdehnert** [comment]
I tried to mark both autoconf and automake as a build dependency in Storm's homebrew formula. Can you retry after `brew update`?

**Comment by merkste** [comment]
I forgot to mention, that I had to install `doxygen` and `hwloc` manually. Unfortunately, it does not yet work. The updated log is 
[install_storm_2.log](https://github.com/moves-rwth/storm/files/1924234/install_storm_2.log)

**Comment by cdehnert** [comment]
The error is still the same. As it is working on other machines for us, I'm starting to suspect that some packages that are not within our scope of influence are not set up to work correctly for non-standard installation paths of homebrew. I know it's a hassle, but do you have the option of reinstalling homebrew with the default Cellar location (/usr/local/Cellar)? From your log, I can, for example, tell that carl does not find ginac and tries to use its shipped version despite the fact that carl has ginac as a homebrew dependency. That leads me to believe that ginac is not installed in a location that is in the usual paths and similar things might happen for other packages as well.

I also marked `'autoconf` and `automake` as build dependencies of carl, so you could try installing carl with
```
brew install carl --with-thread-safe --with-cln --with-ginac -vd
```
but I would be somewhat surprised if that solves the issue.

Also: what does `brew info ginac` print, is it installed?

**Comment by merkste** [comment]
Ok, moving homebrew to /usr/local is bit more involved, since I'd rather not break my Macports installation. I'll try it next week.

**Comment by merkste** [comment]
Ok, it works now. The solution was indeed to install brew to its standard location. Otherwise, certain libs won't be found. The good news: So far it does not interfere with my MacPorts installation. Though, I am using a separate user account for Storm that does not have MP in it's path.
Maybe you could add a comment to the brew section of install manual, stating this conflict?

**Comment by volkm** [comment]
Can you clarify what "the same problem" means? Is your homebrew also not installed in the standard location? In this case, we have not found a solution yet, but installing brew to the standard location should solve the problem.
If you encountered a different error with homebrew, I suggest to open a new issue and we can discuss it there.
