### ISSUE TITLE
Missing check for eigen3

### ISSUE THREAD

**Issue by spacefrogg** [moves-rwth/storm#20]
The check for eigen3 is missing or incomplete.

The build fails unexpectedly if eigen3 is not available on the build system.

**Comment by cdehnert** [comment]
Hi spacefrogg,

can you try to be more specific?

* What were you trying to do precisely?
* What went different from what you'd expect?
* At what stage did this happen?
* What output and/or logs (cmake, etc.) are relevant to the problem?
* What is the host system?

Without this information it will be hard to find out what is the problem.

Thanks,
Chris

**Comment by cdehnert** [comment]
We could identify an issue that is related to eigen3.

What happens is that when our dependency carl is built and eigen3 is not preinstalled and it happens to be a macOS system, then the Fortran compiler is not properly detected and causes the built of eigen to fail.

If this happened to be your problem, please follow
```
http://www.stormchecker.org/documentation/installation/manual-configuration.html#carl
```
and build the current carl master on your system. Reconfiguring Storm in a clean build folder using cmake should then pick up on the carl version you built yourself.

**Comment by spacefrogg** [comment]
I'm closing this issue, as I cannot reproduce it anymore.
