### ISSUE TITLE
storm-conv has issue with single state variable

### ISSUE THREAD

**Issue by PorterGiles123** [moves-rwth/storm#205]
When converting a model from prism to jani, the storm-conv throws an error regarding a single state variable:

The model in specific is [Toggle_10_10.txt](https://github.com/moves-rwth/storm/files/8575559/Toggle_10_10.txt)
 and the command we used to run the converter is as follows:
`storm-conv --input:prism Toggle_10_10.txt -pc --output:tojani Toggle_10_10.jani`

The output of the command:
```storm-conv --input:prism Toggle_10_10.sm -pc --output:tojani Toggle_10_10.jani
Storm-conv 1.6.4 (dev)

Date: Wed Apr 27 12:29:18 2022
Command line arguments: '--input:prism' Toggle_10_10.sm -pc '--output:tojani' Toggle_10_10.jani
Current working directory: /home/pgiles/prismModels

Parsing PRISM input ...  WARN (Program.cpp:179): The input model is a CTMC, but uses probabilistic commands like they are used in PRISM. Consider rewriting the commands to use Markovian commands instead.
 WARN (Program.cpp:1355): The model uses synchronizing Markovian commands. This may lead to unexpected verification results, because of unclear semantics.
 WARN (Program.cpp:1355): The model uses synchronizing Markovian commands. This may lead to unexpected verification results, because of unclear semantics.
 WARN (Program.cpp:1355): The model uses synchronizing Markovian commands. This may lead to unexpected verification results, because of unclear semantics.
 done. (0.003s seconds).
Converting PRISM Program to JANI model ...  done. (0.000s seconds).
Exporting JANI model ... ERROR (JSONExporter.cpp:667): Expression variable '_A' not known in Jani data structures.
ERROR (storm-conv.cpp:386): An exception caused Storm-conv to terminate. The message of the exception is: InvalidJaniException: Expression variable '_A' not known in Jani data structures.
```

**Comment by tquatmann** [comment]
In Prism, local variables can be **read** globally. However, for JANI we need to move those variables to the global scope.

In this particular case, variable `_A` (which is local to PRISM module `_A`) needs to be made global as it is read in module `reaction_rates`.
Somehow, storm doesn't properly detect this here. We're going to fix this.

As a workaround, you can add the command line flag `--globalvars` which simply enforces all variables to be global. As far as I can see, this has to be the case anyway for your model.

Please let me know if this workaround works for you.
