### ISSUE TITLE
Failed test step when installing storm 

### ISSUE THREAD

**Issue by lf9u** [moves-rwth/storm#21]
Hi, I'm trying to install Storm in my MacBook from source. Everything worked, however when I run the test step "make check", it shows that 

93% tests passed, 1 tests failed out of 14

Total Test time (real) = 371.69 sec

The following tests FAILED:
	 11 - run-test-utility (Failed)
Errors while running CTest
make[3]: *** [CMakeFiles/check] Error 8
make[2]: *** [CMakeFiles/check.dir/all] Error 2
make[1]: *** [CMakeFiles/check.dir/rule] Error 2
make: *** [check] Error 2

What might be the reason that fails the test and how to fix the problem?

Thanks

**Comment by cdehnert** [comment]
Hi Lu,

could you provide us with the output you get when executing the binary `test-utility` from Storm's binary folder? That should shed some light on what is going wrong here.

Thanks,
Chris

**Comment by lf9u** [comment]
This is the output of executing the binary test-utility 

$ ./test-utility 
[==========] Running 16 tests from 3 test cases.
[----------] Global test environment set-up.
[----------] 6 tests from GraphTest
[ RUN      ] GraphTest.SymbolicProb01_Cudd
[       OK ] GraphTest.SymbolicProb01_Cudd (299 ms)
[ RUN      ] GraphTest.SymbolicProb01_Sylvan
[       OK ] GraphTest.SymbolicProb01_Sylvan (789 ms)
[ RUN      ] GraphTest.SymbolicProb01MinMax_Cudd
[       OK ] GraphTest.SymbolicProb01MinMax_Cudd (129 ms)
[ RUN      ] GraphTest.SymbolicProb01MinMax_Sylvan
[       OK ] GraphTest.SymbolicProb01MinMax_Sylvan (1624 ms)
[ RUN      ] GraphTest.ExplicitProb01
[       OK ] GraphTest.ExplicitProb01 (107 ms)
[ RUN      ] GraphTest.ExplicitProb01MinMax
[       OK ] GraphTest.ExplicitProb01MinMax (60 ms)
[----------] 6 tests from GraphTest (3008 ms total)

[----------] 7 tests from KSPTest
[ RUN      ] KSPTest.dijkstra
[       OK ] KSPTest.dijkstra (20 ms)
[ RUN      ] KSPTest.singleTarget
[       OK ] KSPTest.singleTarget (19 ms)
[ RUN      ] KSPTest.reentry
[       OK ] KSPTest.reentry (21 ms)
[ RUN      ] KSPTest.groupTarget
[       OK ] KSPTest.groupTarget (19 ms)
[ RUN      ] KSPTest.kTooLargeException
[       OK ] KSPTest.kTooLargeException (23 ms)
[ RUN      ] KSPTest.kspStateSet
/Users/lf291/workspace/storm-master/src/test/storm/utility/KSPTest.cpp:90: Failure
Value of: bv
  Actual: bit vector(50/677) [0 1 3 5 7 10 14 19 25 29 33 36 40 44 50 56 62 70 77 85 92 98 104 112 119 127 134 140 146 154 161 169 176 182 188 196 203 211 218 224 230 238 245 253 260 266 272 281 288 296 ]
Expected: referenceBV
Which is: bit vector(50/677) [0 1 2 4 6 9 12 17 22 30 37 45 52 58 65 70 74 77 81 85 92 98 104 112 119 127 134 140 146 154 161 169 176 182 188 196 203 211 218 224 230 238 245 253 260 266 272 281 288 296 ]
[  FAILED  ] KSPTest.kspStateSet (20 ms)
[ RUN      ] KSPTest.kspPathAsList
/Users/lf291/workspace/storm-master/src/test/storm/utility/KSPTest.cpp:101: Failure
Value of: list
  Actual: { 296, 288, 281, 272, 266, 260, 253, 245, 238, 230, 224, 218, 211, 203, 196, 188, 182, 176, 169, 161, 154, 146, 140, 134, 127, 119, 112, 104, 98, 92, 85, 77, ... }
Expected: reference
Which is: { 296, 288, 281, 272, 266, 260, 253, 245, 238, 230, 224, 218, 211, 203, 196, 188, 182, 176, 169, 161, 154, 146, 140, 134, 127, 119, 112, 104, 98, 92, 85, 77, ... }
[  FAILED  ] KSPTest.kspPathAsList (18 ms)
[----------] 7 tests from KSPTest (140 ms total)

[----------] 3 tests from VectorTest
[ RUN      ] VectorTest.sum_if
[       OK ] VectorTest.sum_if (0 ms)
[ RUN      ] VectorTest.max_if
[       OK ] VectorTest.max_if (0 ms)
[ RUN      ] VectorTest.min_if
[       OK ] VectorTest.min_if (0 ms)
[----------] 3 tests from VectorTest (0 ms total)

[----------] Global test environment tear-down
[==========] 16 tests from 3 test cases ran. (3148 ms total)
[  PASSED  ] 14 tests.
[  FAILED  ] 2 tests, listed below:
[  FAILED  ] KSPTest.kspStateSet
[  FAILED  ] KSPTest.kspPathAsList

 2 FAILED TESTS

**Comment by cdehnert** [comment]
The problem here is a test case that is not robust enough. Because of double imprecisions, the k-shortest path can differ between compilers/machines. I have made the test case a bit more robust in commit bb6fb04f72256da82a1a6d19bd1c5c8559a2e0b3.

In any case, the issue you are observing is not threatening any further problems.
