### ISSUE TITLE
Failed test when installing stormpy in Mac OS X 

### ISSUE THREAD

**Issue by cps-interactive** [moves-rwth/storm#22]
Hi, I got the following error message when running the test step after installing stormpy. I suspect that the error may have something to do the python version. My system is Mac OS X 10.13.4, which has a default Python version 2.7.14 and cannot be removed (as required by the system). But I have installed Python 3.6 separately. When I install strompy, I used "python3" command. However, the test session is using python 2.7.14. Is there a way to config stormpy and let python3 be the default version?

$ py.test tests/
============================= test session starts ==============================
platform darwin -- Python 2.7.14, pytest-3.5.0, py-1.5.3, pluggy-0.6.0
rootdir: /Users/lf291/workspace/stormpy, inifile: setup.cfg
collected 0 items / 1 errors                                                   

==================================== ERRORS ====================================
______________________________ ERROR collecting  _______________________________
/usr/local/lib/python2.7/site-packages/py/_path/common.py:377: in visit
    for x in Visitor(fil, rec, ignore, bf, sort).gen(self):
/usr/local/lib/python2.7/site-packages/py/_path/common.py:419: in gen
    if p.check(dir=1) and (rec is None or rec(p))])
/usr/local/lib/python2.7/site-packages/_pytest/main.py:434: in _recurse
    ihook = self.gethookproxy(path)
/usr/local/lib/python2.7/site-packages/_pytest/main.py:338: in gethookproxy
    my_conftestmodules = pm._getconftestmodules(fspath)
/usr/local/lib/python2.7/site-packages/_pytest/config.py:348: in _getconftestmodules
    mod = self._importconftest(conftestpath)
/usr/local/lib/python2.7/site-packages/_pytest/config.py:376: in _importconftest
    raise ConftestImportFailure(conftestpath, sys.exc_info())
E   ConftestImportFailure: ImportError('No module named stormpy._config',)
E     File "/usr/local/lib/python2.7/site-packages/_pytest/assertion/rewrite.py", line 213, in load_module
E       py.builtin.exec_(co, mod.__dict__)
E     File "/usr/local/lib/python2.7/site-packages/py/_builtin.py", line 221, in exec_
E       exec2(obj, globals, locals)
E     File "<string>", line 7, in exec2
E     File "/Users/lf291/workspace/stormpy/tests/dft/conftest.py", line 1, in <module>
E       from configurations import has_dft
E     File "/Users/lf291/workspace/stormpy/tests/configurations.py", line 3, in <module>
E       import stormpy._config as config
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.19 seconds ============================

**Comment by sjunges** [comment]
This issue is not related to storm. I copied your issue to [stormpy issue nr 2](https://github.com/moves-rwth/stormpy/issues/2).
