### ISSUE TITLE
Prism Language issue with mod() function

### ISSUE THREAD

**Issue by stevencarrau** [moves-rwth/storm#221]
This issue is probably an extension of the discussion for C and modulo (https://stackoverflow.com/questions/4003232/how-to-code-a-modulo-operator-in-c-c-obj-c-that-handles-negative-numbers).

The implementation of the built-in function for mod(i,n) does not output the correct values for i if i<0. For example , -1 % 4 should output 3, instead of -1 (currently implemented). PRISM programs that are compatible with the PRISM model checker don't build on storm due to this issue.

One example in a module for rotating a robot (4 directions):

module robot
    ar : [0..3] init 0;
    [left] true -> 1: (ar'=mod(ar-1,4));
    [right] true -> 1:  (ar'=mod(ar+1,4));
endmodule

Throws an issue when ar=0 -> ar'=-1.

**Comment by sjunges** [comment]
Thanks for catching this Steve!

@tquatmann (and others) I always found mod on negative numbers confusing, but I feel like its a good idea to be aligned with PRISM here (and potentially warn users about the discussion). What do you think?

**Comment by sjunges** [comment]
Summarizing our discussion: We want to investigate the overhead of a solution that transforms `mod(a,b)` into `ITE(a >= 0, mod(a,b), mod(a,b)+b)`; i.e., see whether this negatively affects some of the QVBS benchmarks that have a mod operation *without a negative number*. 

@Marckvdv would you look into this?

**Comment by stevencarrau** [comment]
This is also the way I would implement it. One thing to flag is if a+b< 0 then it may still throw the same issue. But for the module I wrote above the mod(a,b)+b fix would be more than sufficient. I don't see many instances where this would occur though.

**Comment by sjunges** [comment]
Hi,

yes, I assumed that b is still positive. Doing modulo with a negative number as second argument should imo just be forbidden :-). Would be good to check that we handle that situation though.

@stevencarrau it is great if you can use this workaround for now, but I think we want to resolve this issue for future instances as this is not the first time we encounter this discrepancy... ;-). I will flag the thread accordingly.

**Comment by Marckvdv** [comment]
Sure, I can take a look. We'll have to make sure it works for the exact versions too then.
