### ISSUE TITLE
Version issue with `boost` (workaround)

### ISSUE THREAD

**Issue by ifndefJOSH** [moves-rwth/storm#232]
**Short Bug Description**: On systems where a version of `boost` newer than 1.78.0 is installed but 1.78 is not installed, STORM does not properly link, even though an executable is created. On runtime, an error is emitted:
```
./storm: error while loading shared libraries: libboost_filesystem.so.1.78.0: cannot open shared object file: No such file or directory
```
**More Information**: It appears in CMakeLists.txt:269-272 the following code forces an old version of `boost::optional` to be used:
```cmake
# TODO: remove forcing the old version of optional as soon as the related Spirit bug is fixed:
# https://svn.boost.org/trac/boost/ticket/12349
# Fix thanks to: https://github.com/freeorion/freeorion/issues/777
add_definitions(-DBOOST_RESULT_OF_USE_DECLTYPE -DBOOST_OPTIONAL_CONFIG_USE_OLD_IMPLEMENTATION_OF_OPTIONAL)
```
However, I have used STORM (mostly through our project, STAMINA, which is built on top of STORM), using Boost: 1.79 with no issue. I would like to make it clear that **THIS HAS JUST BEEN MY EXPERIENCE. BOOST 1.79 MAY BREAK SOMETHING IN STORM FOR A FEATURE I DON'T GENERALLY USE**. Therefore I have used the following workaround on my system:

**Easy workaround**: Create symlinks that link libboost_*.so.1.* to libboost_*.so.1.78. For my system, which has 1.79 on it, the following script does it for me:

```bash
sudo ln -T /usr/lib/libboost_filesystem.so.1.79.0 /usr/lib/libboost_filesystem.so.1.78.0
sudo ln -T /usr/lib/libboost_system.so.1.79.0 /usr/lib/libboost_system.so.1.78.0
sudo ln -T /usr/lib/libboost_program_options.so.1.79.0 /usr/lib/libboost_program_options.so.1.78.0
sudo ln -T /usr/lib/libboost_regex.so.1.79.0 /usr/lib/libboost_regex.so.1.78.0
sudo ln -T /usr/lib/libboost_unit_test_framework.so.1.79.0 /usr/lib/libboost_unit_test_framework.so.1.78.0
```

**More Permanent Solution**: If the Spirit bug no longer exists in boost, or if it doesn't affect STORM, you could simply remove lines 269-272 in `CMakeLists.txt`, but this needs to be tested before done. I am posting this workaround in this bug report because it worked for me so others can try it and see if it works for them. Note that Boost 1.78 is not available in my `pacman` repositories.

**System Information**:
System type: Linux (Manjaro)
Kernel: 5.18.6-1-MANJARO \#1 SMP PREEMPT_DYNAMIC
Architecture type: x86_64 GNU/Linux
DE: Plasma 5.24.5 
Shell: zsh 5.9 (x86_64-pc-linux-gnu)
Boost Version: 1.79
`git` branch of STORM used: HEAD -> master (hash: a491f13e738ba4491fc26acca351e20bbe9506fc)

**Comment by tquatmann** [comment]
Thanks for making us aware of this issue with newer Boost versions.

Issue #80 is related to this. Back in 2020, Ubuntu 18.04 (which by default installs a boost version that needs this workaround) might still have been in use.
Nowadays, I think this workaround is not needed anymore and only causes trouble.
