### ISSUE TITLE
Abstraction engine not considered in canHandle

### ISSUE THREAD

**Issue by volkm** [moves-rwth/storm#250]
@Vescatur found that using the abstraction engine always prints an error. However, the model-checking query can still be successfully executed.
The problem is that `canHandle` in [utility/Engine.cpp](https://github.com/moves-rwth/storm/blob/master/src/storm/utility/Engine.cpp#L107) is missing the case for this engine.

An example call is the following:
`./bin/storm --jani qcomp/benchmarks/mdp/beb/beb.3-4.jani --janiproperty LineSeized --constants N=3 --core:engine abs`

**Comment by tquatmann** [comment]
The exploration engine seems to be affected, as well.
