### ISSUE TITLE
Error building Z3ExpressionAdapter

### ISSUE THREAD

**Issue by avwhite** [moves-rwth/storm#28]
I hope this is the righ forum to ask for this kind of help in.

I am trying to build storm, but I getting compilation errors. I have attached output of `cmake ..` and `make binaries` below.

[cmake outputt](https://github.com/moves-rwth/storm/files/2120401/cmake-output.txt)
[make binaries output](https://github.com/moves-rwth/storm/files/2120400/build-output.txt)

The problem appears to be Z3ExpressionAdapter.

I have tried to use g++ version 5.4 instead of gcc 8, but the same problem appears. I have z3 version 4.7.1 installed.

**Comment by kleinj** [comment]
It looks like z3 switched their APIs to use `int64_t` and `uint64_t`:

 - https://github.com/Z3Prover/z3/releases/tag/z3-4.7.1
 - https://github.com/Z3Prover/z3/commit/16a2ad9afd8bed86fc7d5d2f40ca3d48b7fedd07

Workaround, with backward compatibility, would probably require a version dependent typedef?

**Comment by sjunges** [comment]
Thank you for the report. Indeed, storm seems to be incompatible with z3 >= 4.7.1.
The quickest fix for you would be to use z3 4.6. 

We will of course look into the issue and fix it in due time.

**Comment by avwhite** [comment]
Thanks for the quick replies. I managed to get it to build by changing `long long` to `int64_t` a couple of places in Z3ExpressionAdapter.cpp. This was easier for me than figuring out how to build and link against a different version of z3 than the one installed on my system (cmake is black magic to me). I havn't checked if any z3 related functionality is borken, but it seems to me that `long long` and `int64_t` are the same thing normal linux machines.

**Comment by sjunges** [comment]
Has been fixed in https://github.com/moves-rwth/storm/commit/cdfa32846463872bfa51a87c86c09bd14e297879 over a year ago.
