### ISSUE TITLE
Support for C++20

### ISSUE THREAD

**Issue by sjunges** [moves-rwth/storm#286]
As a mid-term goal, it would be good to check whether storm can be compiled with C++20. 

Known problems:
- [x] ModernJson, see https://github.com/moves-rwth/storm/issues/284
- [ ] Run tests

**Comment by tquatmann** [comment]
I'm addressing further compilation issues in #447

**Comment by tquatmann** [comment]
I have fixed (or silenced) a couple of warnings we get in c++20 mode here #447 and via the update of parallel hashmap in #448.

My suggestion is to merge these (without the actual switch to c++20), roll out a new release soon, and then do the switch to c++20.

**Comment by sjunges** [comment]
On my machine, there seem to be problems in carl formula that may no longer be relevant after resolving https://github.com/moves-rwth/storm/issues/452
