### ISSUE TITLE
[Build System]  libclang/image not found

### ISSUE THREAD

**Issue by sjunges** [moves-rwth/storm#3]
The following message occurs on Mac Os during building, without explanation.

dyld: Library not loaded: @rpath/libclang.dylib
  Referenced from: /usr/local/bin/doxygen
  Reason: image not found

**Comment by cdehnert** [comment]
Which branch are we talking about? Master successfully built on my OSX machine just recently.

The message indicates a problem with doxygen. Did you try reinstalling it?

**Comment by tjanson** [comment]
What’s the output of:

```sh
ls -ld /Applications/XCode*
xcode-select -p
```

**Comment by sjunges** [comment]
Hmm. The warning is not crucial, but I would like to get rid of the stupid message...

```
ls -ld /Applications/Xcode*    
drwxr-xr-x  3 root  wheel  102 Mar 30 16:57 /Applications/Xcode.app

xcode-select -p
/Applications/Xcode.app/Contents/Developer
```
