### ISSUE TITLE
Constants defined in a properties file can not be parsed

### ISSUE THREAD

**Issue by LeuLinda** [moves-rwth/storm#30]
When defining a constant in a properties file, this can not be parsed. For example, when calling
`storm --prism ./model.prism --prop ./props.prop`
on the model
```
dtmc
const double p = 0.4;
const int N = 5;

module one
x: bool init true;
num_rounds : [0..N] init 0;

[a] x & (num_rounds<N) -> p  : (num_rounds' = num_rounds+1) 
                     + (1-p) : (x' = false) & (num_rounds' = num_rounds+1);
[a] x & (num_rounds=N) -> p  : true 
                     + (1-p) : (x' = false);
endmodule
```

and the properties file 
```
const int k=3;
P=? [F num_rounds = k];
```
the error message "ERROR (FormulaParser.cpp:101): Could not parse formula." arises, but it works fine, when the properties file is given as
```
const int k;
P=? [F num_rounds = k];
```
and the constant k is specified via command line.

**Comment by cdehnert** [comment]
This should be fixed in the current state of master. Can you verify this?
