### ISSUE TITLE
Unexpected behaviour when applying scheduler resulting from makeRowDirac

### ISSUE THREAD

**Issue by AlexBork** [moves-rwth/storm#309]
The `makeRowDirac` method of SparseMatrix  leads to unexpected behaviour when applying a scheduler on an MDP based on the transformed matrix while dropping unreachable states.
In particular, consider the following scenario: I have an MDP on which I computed a scheduler. In this MDP there is a choice (selected by the scheduler) with two successor states where I want to drop the transition to one of those states. For that I make the row into a Dirac distribution and generate a new MDP using the transformed matrix. When applying the scheduler on this new MDP and dropping unreachable states, the following error occurs:
`ERROR (SubsystemBuilder.cpp:109): Expected that in each state, at least one action is selected. Got a deadlock state instead. (violated at STATE)`
where `STATE` is the index of the state the row made Dirac belongs to.

After some testing, I think the error occurs as making the row Dirac does not delete the other entries in the row, but only sets them to zero. Thus, a state may become unreachable and should be dropped, but the matrix entry still exists. In the `SubsystemBuilder`, we iterate over all entries of the matrix and determine 'successors' using the column, so there is a mismatch as a state is unreachable, but still referenced in the matrix.

A possible fix for this issue can be achieved by changing the condition in https://github.com/moves-rwth/storm/blob/77ff8ea757e72cb2c3224b12d4fe5d842c849a82/src/storm/transformer/SubsystemBuilder.cpp#L93
to `!subsystemStates.get(entry.getColumn()) && entry.getValue() != storm::utility::zero<ValueType>()`, i.e. expicitly checking for 'zero entries'.
What do you think?

**Comment by tquatmann** [comment]
The reason why `makeRowDirac` introduces zero entries is that it would otherwise need to touch all subsequent entries of the entire matrix to move them into their new position. This is unexpectedly expensive, especially if there are multiple rows  that one wants to make Dirac. You can call `dropZeroEntries` after modifying the matrix to get rid of those.

Of course, the more fundamental question here is "should zero entries be allowed in a transition matrix?" Currently, many parts of the code seem to assume that all transition entries are non-zero.  Unfortunately, we are not very consistent with this.

**Comment by AlexBork** [comment]
Ah, thanks, I must have overlooked `dropZeroEntries`.
I see the point of not wanting to modify the entire matrix every time a modification may lead to zero entries, in particular if the transformation is only used for computing something.
Would adding an optional flag to transformations that might lead to zero entries that triggers an automatic call of `dropZeroEntries` if set make sense? That way, it is directly visible from the function signature that the default behaviour is to NOT drop the entries. I can imagine that that would make working with the transformations in different contexts easier.

**Comment by sjunges** [comment]
I think that this could indeed be nice.
