### ISSUE TITLE
Is there anyway to create an Exact sparse mdp model ?

### ISSUE THREAD

**Issue by oyendrila-dobe** [moves-rwth/storm#331]
This has been previously discussed in this [stormpy issue](https://github.com/moves-rwth/stormpy/issues/28#issue-783216590). I'm however, unable to locate the corresponding c++ method for exact sparse matrix builder. Is there any existing method that generates the model from PRISM files saving the transitions as Rational numbers? If not, can you point me to the c++ method that can be used to create such a matrix manually?

**Comment by volkm** [comment]
All functions in storm are templated and you can provide the number type you want to use as a template argument. See for example [this test](https://github.com/moves-rwth/storm/blob/master/src/test/storm/modelchecker/multiobjective/SparseDtmcMultiDimensionalRewardUnfoldingTest.cpp#L14) which works with exact (rational) numbers.

You can create a DTMC with rational numbers from a Prism file as follows:
```
std::shared_ptr<storm::models::sparse::Dtmc<storm::RationalNumber>> dtmc =
        storm::api::buildSparseModel<storm::RationalNumber>(program, formulas)->as<storm::models::sparse::Dtmc<storm::RationalNumber>>();
auto matrix = dtmc.getTransitionMatrix();
```

**Comment by oyendrila-dobe** [comment]
Thanks, Matthias. That was really helpful.
