### ISSUE TITLE
Storm exports LOCATION-NOTFOUND

### ISSUE THREAD

**Issue by tquatmann** [moves-rwth/storm#358]
My `stormConfig.cmake` file contained

```
set_target_properties(libsoplex-pic PROPERTIES IMPORTED_LOCATION "LOCATION-NOTFOUND")
```

which means that e.g. stormpy does not compile because it somehow can not link with a library named  `LOCATION-NOTFOUND`

We should somehow make sure that either this is not exported in the first place or at least detected on the stormpy side.

**Comment by tquatmann** [comment]
Yes, this also solves the issue for me. I think there are two sides of this issue:

* Find out and fix why using soplex does this
* Generally make sure that "LOCATION-NOTFOUND" is not exported by any library

**Comment by volkm** [comment]
We are not using `add_imported_library` in the CMake file for soplex. No idea whether this has anything to do with it, but I guess it does not hurt to add it and try whether it changes anything?
