### ISSUE TITLE
Missing exportJani module

### ISSUE THREAD

**Issue by molnartimi** [moves-rwth/storm#36]
In previous releases, there was an `exportJani` module with `--jani-output` option, in the new (1.3.0) version I can't find it. I used it with `--prism2jani` option to convert my prism models into jani language.

What should I do? The prism2jani option is still available, but it seems it has no effect standing by alone.

**Comment by tquatmann** [comment]
We moved the functionality to a separate binary called storm-conv. You can still convert your models, but the commands are slightly different.
You can find some instructions on using storm-conv here:
http://qcomp.org/benchmarks/conversions.html
Please don't hesitate to ask further questions.
We are also always happy to add more models to http://qcomp.org/benchmarks , so please consider to contribute :)
Best,
Tim
