### ISSUE TITLE
Check Eigen Version during Config

### ISSUE THREAD

**Issue by sjunges** [moves-rwth/storm#366]
Errors like

```
$ cat /Users/Mees_1/storm/build/carl-prefix/src/carl-stamp/carl-build-err.log
clang: warning: argument unused during compilation: '-msse' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]
/Users/Mees_1/storm/build/resources/3rdparty/carl_download/source_dir/src/carl/core/rootfinder/EigenWrapper.cpp:3:10: fatal error: 'eigen3/Eigen/Dense' file not found in #include <eigen3/Eigen/Dense>
```

seem to originate from using a `wrong` preinstalled eigen version. It would be helpful to detect such errors during configuration to clarify that this is a problem with the host system. We could e.g. check whether the include compiles (cmake has some nice functions that support these checks).

**Comment by tquatmann** [comment]
I agree, but shouldn't this be an issue of [carl-storm](https://github.com/moves-rwth/carl-storm) ?

**Comment by sjunges** [comment]
Don't we forward the EIGEN version from Storm?

**Comment by tquatmann** [comment]
No, Storm ships it's own eigen version which is currently only used within Storm.
It might be possible to use that also in Carl but that would mean that carl-storm in _some_ way depends on storm (or at least storm's build infrastructure).

**Comment by sjunges** [comment]
Oops.  i added an issue there https://github.com/moves-rwth/carl-storm/issues/17 there and I opened an issue regarding configuring two versions of eigen here: https://github.com/moves-rwth/storm/issues/425
