### ISSUE TITLE
[DEPENDENCY] CUDD Requires a working TeXLive installation - Not listed in Storm's dependencies

### ISSUE THREAD

**Issue by ifndefJOSH** [moves-rwth/storm#388]
I noticed when attempting to build Storm on a machine with an old/out-of-date TeXLive installation that the build command was failing during the CUDD step. It is my understanding that Storm's `CMakeLists.txt` download and install CUDD automatically. However, the CUDD library is built with a GNU Makefile, which also builds documentation for CUDD in PDF format from some LaTeX files. Storm's CMakeLists do not have any check to ensure that a working TeX distribution is installed, such as TeXLive, and if one is not installed, or is sufficiently out of date, the compilation process can fail at the step where CUDD is built. The output seen by the user will instruct them to consult CUDD's build file logs, where they will notice that some LaTeX error has occurred.

**To Reproduce**

- On a Virtual Machine, install a (working) TeXLive distribution
- Remove one of the "core" `.sty` files (e.g, `pdfsymbols.sty`)
- Clone Storm and install its [dependencies](https://www.stormchecker.org/documentation/obtain-storm/dependencies.html) (I used the "recommended", rather than just the "required" to eliminate any possibility it was something related to that.
- Using the recommended `cmake` and `make` build process, attempt to build Storm
- At about 50% of the way through the build process (according to the CMake progress bar) you should get an error in the CUDD build process indicating that an invocation of `make` failed. It will show the command and all of its options in red. This is the invocation of CUDD's makefile. Additionally it will ask the user to consult `<build-path>/resources/3rd-party/cudd-3.0/.../*.log`. When the user  consults said log (namely the `*-out.log` file) it will indicate an error in `pdflatex`.

**More information**

In the [configure.ac](https://github.com/moves-rwth/storm/blob/fd1fe7091df062835143fa78bed3e91106e5207a/resources/3rdparty/cudd-3.0.0/configure.ac) file for CUDD, lines 48 and 56-59, the file checks for the existence of the `pdflatex` executable and if it exists, attempts to build documentation for CUDD in LaTeX form.

Operating System: Ubuntu 22.04.2 LTS
Architecture: x86_64
Kernel: 5.15.0-43-generic
CPU: AMD Ryzen Threadripper 1920X

CMake Version: 3.22.1
GNU Make Version: 4.3
Storm Verison: 1.8.0

**A Potential Fix**

You could change the `pdflatex` invocation to use `-interaction=nonstopmode`. Not totally sure if this will work but it will prevent it from hanging.
```
pdflatex -interaction=nonstopmode $LATEX_FILE
```

**Another fix**

Just not build CUDD documentation in LaTeX format.

**Comment by sjunges** [comment]
Thanks. I will follow the suggestion to not compile the CUDD documentation at this point. I dont see a reason to actually compile it. 

I also opend a PR to fix this.
