### ISSUE TITLE
nondet-selection

### ISSUE THREAD

**Issue by alebugariu** [moves-rwth/storm#389]
Hi,
   I am trying to use Storm on the [reentrant-queues](https://github.com/ahartmanns/qcomp/tree/122afb7f38bc78d239372ac5764a74434ec2a13a/benchmarks/ma/reentrant-queues) example from the Quantitative Verification Benchmark Set. Running `./storm --qvbsroot <path-to>/qcomp/benchmarks --qvbs reentrant-queues` produces an error:
   
```
ERROR (JaniParser.cpp:134): Storm does not support the model feature nondet-selection
ERROR (storm.cpp:23): An exception caused Storm to terminate. The message of the exception is: NotSupportedException: Storm does not support the model feature nondet-selection
```
   Is there a why in which I could enable this feature or is it no longer supported?
   Thank you very much!

**Comment by tquatmann** [comment]
Hi,
[The modest tool set](https://modestchecker.net) includes a conversion tool to translate the jani model to an equivalent model without `nondet-selection`. Unfortunately, this is the only way Storm supports such models.

So you'd have to download and install modest and use something like the following command (see also [this](https://qcomp.org/benchmarks/#reentrant-queues) page):
```
./modest moconv reentrant-queues.modest -O reentrant-queues.jani
```

**Comment by alebugariu** [comment]
Unfortunately the conversion does not work for me either. With modest  v3.1.237-g2f62162c7 there seems to be a parsing error:
```
./modest moconv reentrant-queues.modest -O reentrant-queues.jani
Parsing reentrant-queues.modest...                                                                              

reentrant-queues.modest:(20,36): error: Expected "S", "T" or "X".
```

**Comment by volkm** [comment]
I think this is an issue with the Modest file. I will contact the maintainer.

**Comment by tquatmann** [comment]
Sorry, I initially copied the wrong command line from [this](https://qcomp.org/benchmarks/#reentrant-queues) page. I edited the reply above (to not confuse future visitors of this issue). Note that The `moconv` tool processes the `reentrant-queues.jani` file in my new command line.

Still good to make the modest maintainer aware of the parsing error :)
