### ISSUE TITLE
cln has #define As; conflict with other libraries

### ISSUE THREAD

**Issue by flyingkukri** [moves-rwth/storm#394]
in RationalNumberAdapter.h line 8 <cln/cln.h> is included. 
However cln in line 269 defines As.
https://www.ginac.de/CLN/cln.git/?p=cln.git;a=blob;f=include/cln/number.h;h=67f68899a6926eca49722f012d0a20d159162c57;hb=HEAD#l269

This conflicts for example with mlpack:
https://github.com/mlpack/mlpack/issues/3501

This can be fixed by adding 
`#undef As`
before including mlpack.

**Comment by sjunges** [comment]
Hi,

Thanks for this report. However, notice that we are not the developers or maintainers of CLN. 
As suggested by @conradsnicta in https://github.com/mlpack/mlpack/issues/3501, you may want to reach out to them to avoid this issue. 

Best,
Sebastian

**Comment by flyingkukri** [comment]
Hi,

yeah I know, just in case someone gets a similar issue in the future, I wanted to post this here. Or should only fixable bugs get posted?

**Comment by sjunges** [comment]
I added a message on the CLN mailing list:

https://www.ginac.de/pipermail/cln-list/2023-October/000819.html

**Comment by sjunges** [comment]
I am closing this for now. There is a workaround and it is really up to the CLN developers to fix this. I do not see a reason to create a local fork unless more people start complaining :-)
