### ISSUE TITLE
jit always links with carl

### ISSUE THREAD

**Issue by tquatmann** [moves-rwth/storm#44]
Jit currently seems to link with all the glory of Carl, which is not necessary if ValueType is double. Fixing this should reduce build times for jit.

**Comment by volkm** [comment]
Some notes:
- Linking with carl could be easily disabled [here](https://github.com/moves-rwth/storm/blob/master/src/storm/builder/jit/ExplicitJitJaniModelBuilder.cpp#L124) by adding
`if (std::is_same<ValueType, storm::RationalFunction>::value)`
- The main culprit is including `RationalFunctionAdapter.h` in `NumberTraits.h`. Disabling this seems to drastically decrease the compilation time. However, we possibly need to make carl optional again and reactivate `STORM_HAVE_CARL`.

**Comment by sjunges** [comment]
This issue is resolved by https://github.com/moves-rwth/storm/pull/292 by removing the functionality whatsoever.
