### ISSUE TITLE
Accelerate CI by precompiling spot

### ISSUE THREAD

**Issue by sjunges** [moves-rwth/storm#442]
I checked the compile times today in github actions. It seems that we spent roughly 330 seconds building spot, which accounts to roughly 10% of the CompilerTests test times. I think that we can avoid those timings by preinstalling spot into the docker file?

This is of course not urgent in any way :-)

**Comment by volkm** [comment]
My proposal is to create a Dockerfile with all optional Storm dependencies (MathSAT, Spot, maybe Storm-Carl) and use this as base for the in-depth tests.
