### ISSUE TITLE
storm compilation error

### ISSUE THREAD

**Issue by ochipara** [moves-rwth/storm#45]
Hi,

I am trying to install storm on osx. I have tried to use brew and I get the following compilation error:

Last 15 lines from /Users/ochipara/Library/Logs/Homebrew/stormchecker/02.make:
                                            ^
/tmp/stormchecker-20190508-86606-mclz9y/storm-1.3.0/src/storm/builder/DdJaniModelBuilder.cpp:902:24: note: in instantiation of member function 'storm::builder::CombinedEdgesSystemComposer<storm::dd::DdType::Sylvan, carl::RationalFunction<carl::FactorizedPolynomial<carl::MultivariatePolynomial<cln::cl_RA, carl::MonomialComparator<&carl::Monomial::compareGradedLexical, true>, carl::StdMultivariatePolynomialPolicies<carl::NoReasons, carl::NoAllocator> > >, true> >::buildAutomatonDd' requested here
                return buildAutomatonDd(composition.getAutomatonName(), data.empty() ? actionInstantiations : boost::any_cast<ActionInstantiations const&>(data), inputEnabledActionIndices);
                       ^
/tmp/stormchecker-20190508-86606-mclz9y/storm-1.3.0/src/storm/builder/DdJaniModelBuilder.cpp:2090:58: note: in instantiation of member function 'storm::builder::CombinedEdgesSystemComposer<storm::dd::DdType::Sylvan, carl::RationalFunction<carl::FactorizedPolynomial<carl::MultivariatePolynomial<cln::cl_RA, carl::MonomialComparator<&carl::Monomial::compareGradedLexical, true>, carl::StdMultivariatePolynomialPolicies<carl::NoReasons, carl::NoAllocator> > >, true> >::visit' requested here
            CombinedEdgesSystemComposer<Type, ValueType> composer(preparedModel, actionInformation, variables, rewardVariables);
                                                         ^
/tmp/stormchecker-20190508-86606-mclz9y/storm-1.3.0/src/storm/storage/dd/DdManager.h:68:30: note: declared as a non-template here
            Bdd<LibraryType> getBddZero() const;
                             ^
4 errors generated.
make[2]: *** [src/storm/CMakeFiles/storm.dir/builder/DdJaniModelBuilder.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [src/storm/CMakeFiles/storm.dir/all] Error 2
make: *** [all] Error 2

Attached is the error log showing additional details from the compilation process. I get the same error if I try to compile from source. 

[02.make.log](https://github.com/moves-rwth/storm/files/3157718/02.make.log)

**Comment by volkm** [comment]
Hi,
the latest release of Storm apparently contains a compilation error which prevents a successful build. As this issue is already fixed in the current master branch I suggest to use this branch at the moment:
`brew install stormchecker --HEAD`
We will try to release a new version of Storm soon and will include this bugfix.

**Comment by ochipara** [comment]
Thank you that solved the problem.
