### ISSUE TITLE
Building with system carl fails

### ISSUE THREAD

**Issue by hobborg** [moves-rwth/storm#53]
OS: Linux 5.2.9-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 16 11:29:43 UTC 2019 x86_64 GNU/Linux
The CARL library comes in a broken AUR package: you get to choose between `carl` and `git-carl`, both equally old (2017), both equally broken.
Downloaded carl from the git repo, version 19.06. Built ok, installed in default path (`/usr/local/lib64`)
Compiling storm fails with the error:
```
CMake Error at resources/3rdparty/CMakeLists.txt:237 (if):
  if given arguments:
    "STREQUAL" "carlLOCATION-NOTFOUND"
  Unknown arguments specified
```
Fix: in `resources/3rdparty/CMakeLists.txt` change line 237 from:
```if(${carlLOCATION} STREQUAL "carlLOCATION-NOTFOUND")```
to:
```if("${carlLOCATION}" STREQUAL "carlLOCATION-NOTFOUND")```
i.e. wrap `${carlLOCATION}` in double quotes.
My cmake version is 3.15.2

**Comment by sjunges** [comment]
Regarding the first part... yes, the AUR is not up to date, but we are not the maintainers of that. We would of course be happy if you would take over the maintenance.

> CMake Error at resources/3rdparty/CMakeLists.txt:237 (if):
>   if given arguments:
>     "STREQUAL" "carlLOCATION-NOTFOUND"
>   Unknown arguments specified

Thanks for the fix, I will push this soon.

**Comment by hobborg** [comment]
My pleasure!
Regarding maintenance, I should first take over maintenance of my 
crumbling academic career  :/
--
(memento mori)

**Comment by sjunges** [comment]
Fixed in [this commit](https://github.com/moves-rwth/storm/commit/28f8c9d8218009ddadaf7e5a532262ec99a75124)
