### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [moves-rwth/storm#532]
[An extra null pointer check is not needed in functions](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") like the following.
- [AddIterator destructor](https://github.com/moves-rwth/storm/blob/66981bb05f2a5ff67ea89ac6709d3aab581c9a16/src/storm/storage/dd/cudd/CuddAddIterator.cpp#L85-L94)
- [BitVector destructor](https://github.com/moves-rwth/storm/blob/66981bb05f2a5ff67ea89ac6709d3aab581c9a16/src/storm/storage/BitVector.cpp#L137-L141)

**Comment by sjunges** [comment]
Thanks for the report!

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/moves-rwth/storm/commit/011166332113cb9b259ae2c8f56f9c0e373683ac "Deletion of redundant pointer checks").
