### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [moves-rwth/storm#533]
Would you like to [wrap any pointers](https://github.com/moves-rwth/storm/blob/66981bb05f2a5ff67ea89ac6709d3aab581c9a16/src/storm-gspn/parser/GspnParser.cpp#L15-L74 "Update candidate: GspnParser::parse()") with the class template “[std::unique_ptr](https://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "Description for the usage of smart pointers")”?

**Comment by sjunges** [comment]
Not *any*, but we do of course welcome increased memory safety.

**Comment by elfring** [comment]
:thought_balloon: Would you become interested to [use a development tool like “clang-tidy” for corresponding source code adjustments](https://clang.llvm.org/extra/clang-tidy/checks/cppcoreguidelines/owning-memory.html "Checking handling of pointers")?

**Comment by sjunges** [comment]
We welcome pull requests that improve the code quality. Integrating CI based on clang-tidy is not a priority right now.

**Comment by elfring** [comment]
:crystal_ball: Will a special data representation trigger [another bit of collateral evolution](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#r11-avoid-calling-new-and-delete-explicitly "Recommendations around allocation and deallocation")?
https://github.com/moves-rwth/storm/blob/66981bb05f2a5ff67ea89ac6709d3aab581c9a16/src/storm-gspn/parser/GspnParser.cpp#L15-L74
