### ISSUE TITLE
Installing storm on Amazon AWS

### ISSUE THREAD

**Issue by mcubuktepe** [moves-rwth/storm#54]
Hello,

I am trying to install storm on an Amazon AWS client, and I am running into errors while executing cmake .. command in the build folder. I am attaching the message on the terminal:

[ec2-user@ip-172-31-14-157 build]$ cmake ..
-- Storm - CMake install dir: /usr/local/lib/CMake/storm
-- Storm - Building RELEASE version.
-- Storm - Could not find ccache.
-- Storm - Detected operating system Linux.
-- Storm - Assuming extension for shared libraries: .so
-- Storm - Assuming extension for static libraries: .a
-- Storm - Build static libraries.
-- Storm - Enabling link-time optimizations.
-- Storm - Using compiler configuration gcc 7.3.1.
CMake Warning at /usr/local/share/cmake-3.7/Modules/FindBoost.cmake:744 (message):
  Imported targets not available for Boost version 107000
Call Stack (most recent call first):
  /usr/local/share/cmake-3.7/Modules/FindBoost.cmake:848 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/share/cmake-3.7/Modules/FindBoost.cmake:1435 (_Boost_MISSING_DEPENDENCIES)
  resources/3rdparty/CMakeLists.txt:62 (find_package)
  CMakeLists.txt:386 (include)

CMake Warning at /usr/local/share/cmake-3.7/Modules/FindBoost.cmake:744 (message):
  Imported targets not available for Boost version 107000
Call Stack (most recent call first):
  /usr/local/share/cmake-3.7/Modules/FindBoost.cmake:848 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/local/share/cmake-3.7/Modules/FindBoost.cmake:1435 (_Boost_MISSING_DEPENDENCIES)
  resources/3rdparty/CMakeLists.txt:62 (find_package)
  CMakeLists.txt:386 (include)

-- Storm - Using boost 107000 (library version 1_70).
-- Storm - Including ExprTk.
-- Storm - Including Sparsepp.
-- Storm - Including ModernJSON.
-- Could NOT find z3 (missing:  Z3_LIBRARY Z3_INCLUDE_DIR) 
CMake Warning at resources/3rdparty/CMakeLists.txt:180 (message):
  Storm - Z3 not found.  Building of Prism/JANI models will not be supported.
Call Stack (most recent call first):
  CMakeLists.txt:386 (include)

-- Storm - Using shipped version of glpk.
-- Storm - Linking with glpk 4.57
-- Storm - Linking with CUDD 3.0.0.
CMake Error at resources/3rdparty/CMakeLists.txt:241 (message):
  File /home/ec2-user/storm/build/resources/3rdparty/carl/libcarl.so.14.18
  does not exist, did you build carl?
Call Stack (most recent call first):
  CMakeLists.txt:386 (include)

-- Storm - Found carl using master14 branch.
-- Storm - Use system version of carl.
-- Storm - Linking with preinstalled carl 14.18.10-g2c4f69a1 (include: /home/ec2-user/storm/build/resources/3rdparty/carl_download/source_dir/src, library lib_carl, CARL_USE_CLN_NUMBERS: ON, CARL_USE_GINAC: ON).
-- Storm - Use shipped version of xerces.
-- Storm - Linking with xercesc.
-- Storm - Using shipped version of sylvan.
-- Storm - Linking with sylvan.
-- Storm - Linking with hwloc .
-- Storm - Version is 1.3.1 (dev) (version 1.3.0 + 3 commits), building from git: 4b56fb137def90f0acdbbdcf5f26f85d85b692d9 (dirty: false).
-- Registered with cmake
-- Configuring incomplete, errors occurred!

I am also attaching the output from CMakeError.log:

Determining if the pthread_create exist failed with the following output:
Change Dir: /home/ec2-user/storm/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_db370/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_db370.dir/build.make CMakeFiles/cmTC_db370.dir/build
gmake[1]: Entering directory `/home/ec2-user/storm/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_db370.dir/CheckSymbolExists.c.o
/usr/bin/cc     -o CMakeFiles/cmTC_db370.dir/CheckSymbolExists.c.o   -c /home/ec2-user/storm/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_db370
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_db370.dir/link.txt --verbose=1
/usr/bin/cc      -rdynamic  CMakeFiles/cmTC_db370.dir/CheckSymbolExists.c.o  -o cmTC_db370 -rdynamic
CMakeFiles/cmTC_db370.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_db370] Error 1
gmake[1]: Leaving directory `/home/ec2-user/storm/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_db370/fast] Error 2

File /home/ec2-user/storm/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/ec2-user/storm/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_6f752/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_6f752.dir/build.make CMakeFiles/cmTC_6f752.dir/build
gmake[1]: Entering directory `/home/ec2-user/storm/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_6f752.dir/CheckFunctionExists.c.o
/usr/bin/cc    -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_6f752.dir/CheckFunctionExists.c.o   -c /usr/local/share/cmake-3.5/Modules/CheckFunctionExists.c
Linking C executable cmTC_6f752
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_6f752.dir/link.txt --verbose=1
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -rdynamic  CMakeFiles/cmTC_6f752.dir/CheckFunctionExists.c.o  -o cmTC_6f752 -rdynamic -lpthreads
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_6f752] Error 1
gmake[1]: Leaving directory `/home/ec2-user/storm/build/CMakeFiles/CMakeTmp'
gmake: **

Thanks a lot for the help.

**Comment by mcubuktepe** [comment]
Hi, I was able to make a bit of progress, but stuck on this issue while running make command on /build folder.

make[2]: *** No rule to make target `/home/ec2-user/carl/build/resources/lib/libboost_filesystem.so', needed by `lib/libstorm.so'.  Stop.
make[1]: *** [src/storm/CMakeFiles/storm.dir/all] Error 2
make: *** [all] Error 2
[ec2-user@ip-172-31-14-157 build]$ ls
bin                      Doxyfile           stormConfig.cmake
CMakeCache.txt           googletest-prefix  stormConfig.install.cmake
CMakeFiles               include            stormConfigVersion.cmake
cmake_install.cmake      l3pp_ext-prefix    stormTargets.cmake

Here's the content of /home/ec2-user/carl/build/resources/lib/:

**Comment by volkm** [comment]
Hi,
the `is_equal_to_one` function is not available in Boost 1.70 any more. This was fixed in the current master branch by commit 1e36864. I guess you are using the stable branch and suggest to just locally remove this function in the `ExpressionParser` for the moment.
