### ISSUE TITLE
Doxygen/Problem with older version of CMAKE

### ISSUE THREAD

**Issue by sjunges** [moves-rwth/storm#55]
I recently got the following error message (on a machine which I can no longer access).

> CMake Error at resources/doxygen/CMakeLists.txt:25 (doxygen_add_docs):
>   Unknown CMake command "doxygen_add_docs".

The same issue as: https://github.com/epfl-ecps/channelflow/issues/13

Thus, we should add a check that the cmake version is up-to-date, or block the functionality in that file.

**Comment by volkm** [comment]
Should be fixed with bf735f0.
