### ISSUE TITLE
Error linking with CUDD 3.0.0.

### ISSUE THREAD

**Issue by xwang2775** [moves-rwth/storm#583]
Hello,

When I try cmake in storm, I get error linking with CUDD. I have successfully installed `carl-storm `and `pycarl-2.2.0`

```
-- Storm - Linking with CUDD 3.0.0.
CMake Error at resources/3rdparty/CMakeLists.txt:310 (get_target_property):
  get_target_property() called with non-existent target "lib_carl".
Call Stack (most recent call first):
  CMakeLists.txt:473 (include)


CMake Error at resources/3rdparty/CMakeLists.txt:325 (message):
  File does not exist, did you build carl?
Call Stack (most recent call first):
  CMakeLists.txt:473 (include)


-- Configuring incomplete, errors occurred!

```

`resources/3rdparty/` here

```
(env) (/Users/wangxinyu/RAG/llm_agent/RAG-with-Verification/rag) wangxinyu@wangxinyu 3rdparty % ls
StormEigen-3.4.0        cudd-3.0.0              z3

```

`carl` here

`/Users/wangxinyu/RAG/RAG-with-Verification/carl-storm/src/carl/`

**Comment by volkm** [comment]
Can you provide the complete output of the configure step `cmake ..`?

**Comment by volkm** [comment]
You can set the carl directory with either `carl_DIR` or with `STORM_CARL_DIR_HINT`. Maybe that already helps.

It also seems like you are using an older version of Storm. Can you try using the latest version from the master branch? It comes with the latest support for Apple Silicon.

**Comment by xwang2775** [comment]
It was solved, thanks!

**Comment by xwang2775** [comment]
It was solved, thanks!
