### ISSUE TITLE
Support for z3 version 4.4.1

### ISSUE THREAD

**Issue by sjunges** [moves-rwth/storm#59]
Dear all,

what is the minimal z3 version that storm currently supports?
In particular, on Ubuntu 18.04 with z3 4.4.1, we get the following error which, I think, stems from the z3 version. 

> 
>  In member function ‘storm::expressions::Expression storm::adapters::Z3ExpressionAdapter::translateExpression(const z3::expr&)’:
> .../storm/adapters/Z3ExpressionAdapter.cpp:148:80: error: invalid conversion from ‘storm::adapters::Z3_SIGNED_INTEGER* {aka long long int*}’ to ‘int64_t* {aka long int*}’ [-fpermissive]
>                                      if (Z3_get_numeral_int64(expr.ctx(), expr, &value)) {

**Comment by volkm** [comment]
Similar to #28. Do we need to make some further changes as in cdfa32846463872bfa51a87c86c09bd14e297879?

**Comment by volkm** [comment]
Just for reference:
- Ubuntu 18.04 LTS, Ubuntu 19.04, Debian 9 and Debian 10 are shipped with z3 version 4.4.1
- Ubuntu 19.10 is shipped with z3 version 4.8.4

**Comment by sjunges** [comment]
Okay, seems like z3 4.4.1 will be around for a while. 

But if I understand this correctly, than STORM_Z3_API_USES_STANDARD_INTEGERS should be switched on for version 4.4.1 (and it seems that right now, it is OFF unless NOT "${Z3_VERSION}" VERSION_LESS "4.7.1".

I currently have no machine on which to test this.

**Comment by tquatmann** [comment]
I just set up a fresh VM with ubuntu 18.04 (using z3 4.4.1 and Storm 1.4.1) and I was able to compile and use Storm without any issues. I'm closing this issue since

* it does not seem to be reproducable
* there is a straightforward workaround: Install a more recent z3 version
