### ISSUE TITLE
Pick a new eigen commit and use that instead of outdated Eigen 3.4

### ISSUE THREAD

**Issue by sjunges** [moves-rwth/storm#601]
No new stable release since, but Eigen 3.4 is old.

Addresses among others https://github.com/moves-rwth/storm/issues/416 and https://github.com/moves-rwth/storm/issues/162

**Comment by volkm** [comment]
One possible candidate for an Eigen commit could be the version [3.4.1 commit](https://gitlab.com/libeigen/eigen/-/commit/bae907b8f6078b1df290729eef946360315bd312) on the 3.4 branch in Eigen

**Comment by tquatmann** [comment]
Done in #611
