### ISSUE TITLE
Is xerces-c optional?

### ISSUE THREAD

**Issue by sjunges** [moves-rwth/storm#67]
Hi,

I failed to compile storm without xerces-c, likely because CMake reported that it was found. 
Before I investigate/fix further: Is xerces-c still considered optional, or not?

Best,
Sebastian

**Comment by volkm** [comment]
xerces-c should still be optional. You have to set the CMake option `XML_SUPPORT` to `OFF`. I just checked and with this configuration, Storm should be built without xerces-c.

**Comment by sjunges** [comment]
Okay, this behavior is different from Z3, there we build storm anyway (despite that without Z3, there is not that much you can do), whereas without xerces we do not build unless you set another option. 

I think the easiest solution would be that we hint at switching off xml support when xerces-c is not found.... but it is still an error message. We could also warn people that XML support is not available and continue building, just like with z3. 

Also, xml support is only required for the parsers?

**Comment by volkm** [comment]
I think xml support is only necessary for both the pnpro and pnml parser. As xerces is only required for the GSPN part it should be possible to build Storm without it.

I would favour a handling similar to Z3. My proposal would be to remove the CMake option for XML support and implicitly set it dependent on whether xerces-c was found or not. If xerces is found, we build Storm with XML support, otherwise we give a warning but still continue building Storm.

**Comment by sjunges** [comment]
I think that part of the problem is that we also are able to built xerces-c ourselves. 
It seems that that part is currently broken, and given the minor role of GSPN parsers in our project, I would like to drop the support for building xerces from source. 

I am still investigating why storm does not compile without xerces. But that would be the next step.

**Comment by volkm** [comment]
I agree that we should not ship the xerces sources in the future. As z3 is optional and we do not provide its sources, we should do the same for xerces. Having fewer shipped sources also helps in keeping the 3rd party libraries up to date, because we let the OS take care of it.

**Comment by sjunges** [comment]
Done. One might now argue that building storm-gspn is currently not that useful without xerces, but I think that this is a minor concern for now, and maybe we will also support another non-xml based format eventually, which would then again make sense.
