### ISSUE TITLE
In exact mode, MDP result is not exact

### ISSUE THREAD

**Issue by kleinj** [moves-rwth/storm#7]
For lec15mdp.nm from the PRISM test suite (stable branch):

```
storm --prism ./pmc/lec15mdp.nm --prop 'Pmax=? [ F s=1|s=3|s=4 ]'  --exact --verbose
Storm 1.1.1 (dev)

[...]
Model checking property Pmax=? [F (((s = 1) | (s = 3)) | (s = 4))] ...
 INFO (SparseMdpPrctlHelper.cpp:125): Found 4 'no' states.
 INFO (SparseMdpPrctlHelper.cpp:126): Found 1 'yes' states.
 INFO (SparseMdpPrctlHelper.cpp:127): Found 1 'maybe' states.
 INFO (IterativeMinMaxLinearEquationSolver.cpp:421): Iterative solver converged after 27 iterations.
 INFO (cli.cpp:622): Result (for initial states):
Result (for initial states):  INFO (cli.cpp:564): 11175859456989514707/14901161193847656250 (approx. 0.749999)
11175859456989514707/14901161193847656250 (approx. 0.7499992324) INFO (cli.cpp:610):
```

When I select policy iteration as the minmax method, the correct value is obtained:

```
storm --prism ./pmc/lec15mdp.nm --prop 'Pmax=? [ F s=1|s=3|s=4 ]'  --exact --method pi --verbose

Storm 1.1.1 (dev)

[...]
Model checking property Pmax=? [F (((s = 1) | (s = 3)) | (s = 4))] ...
 INFO (SparseMdpPrctlHelper.cpp:125): Found 4 'no' states.
 INFO (SparseMdpPrctlHelper.cpp:126): Found 1 'yes' states.
 INFO (SparseMdpPrctlHelper.cpp:127): Found 1 'maybe' states.
 INFO (EigenLinearEquationSolver.cpp:321): Solving linear equation system (1 rows) with with rational numbers using LU factorization (Eigen library).
 INFO (EigenLinearEquationSolver.cpp:321): Solving linear equation system (1 rows) with with rational numbers using LU factorization (Eigen library).
 INFO (IterativeMinMaxLinearEquationSolver.cpp:421): Iterative solver converged after 2 iterations.
 INFO (cli.cpp:622): Result (for initial states):
Result (for initial states):  INFO (cli.cpp:564): 3/4 (approx. 0.75)
3/4 (approx. 0.75) INFO (cli.cpp:610):
```

My guess would be that somehow the standard value iteration setting is not changed to policy iteration?

**Comment by cdehnert** [comment]
Actually, this behaviour is a bit intended. "—exact” mode merely means: use rational numbers rather than double… Technically, we can set the technique to policy iteration as well, but that’s then kind of in contradiction with what the options say (default: “vi”)...

**Comment by kleinj** [comment]
I see, makes sense that one might also be interested in an approximate value iteration results but with exact computations. From a user perspective I think it would be better to ensure that the defaults will actually lead to exact results, and print warnings otherwise (e.g., "value iteration selected, results will be approximations").

Do you technically have a way to distinguish default options from non-default ones? Then you could just have vi be the default in normal circumstances, but pi if in exact mode?

**Comment by cdehnert** [comment]
So I took up your suggestion. As of commit 8cdbf281fae2e4f97eea6c6427d2b4a19193ad80 the behaviour is as follows:

* if no method was explicitly requested and exact mode was turned on: issue a warning that the method is implicitly changed,
* if a method was explicitly set and it's not policy iteration and exact mode was turned on: issue a warning that the selected method does not guarantee exact results.

Does this solve the issue?

**Comment by kleinj** [comment]
Yes, now works as expected. Thanks!
