### ISSUE TITLE
Expressing nested reachability properties

### ISSUE THREAD

**Issue by vanhecke1** [moves-rwth/storm#72]
Hi,

I was curious if I can express nested reachability properties such as "Eventually a then eventually b, F ( a & ( F b))" or similar properties such as "Eventually a and eventually b, F a & F b" in storm. Thank you.

**Comment by tquatmann** [comment]
Hi,

Storm supports (nested) PCTL formulas but unfortunately no probabilistic LTL formulas.
This means that Storm can deal with queries like 

> What is the probability to reach a state that is labeled with `a` and from which `b` is reached with probability at least 0.9 (`P=? [ F "a" & P>=0.9 [F "b"] ]`)

However, properties like
> What is the probability to first reach a state labeled with `a` and then reach a state labeled with `b` 

are not possible right now.

(I'm closing this issue but feel free to re-open in case you have further questions regarding this topic)
