### ISSUE TITLE
State valuations do not properly handle transient variables

### ISSUE THREAD

**Issue by tquatmann** [moves-rwth/storm#73]
The state valuations do not seem to store the value of transient JANI variables correctly. This is an issue, e.g., when exporting a scheduler with state valuations.

**Comment by sjunges** [comment]
At the same time, state valuations do hold values for constants etc, which is a waste of memory.... I think the clean way around it would be to store 'interesting values', but right now it is just a mapping of all variables in the expression manager (without actually storing them).
