### ISSUE TITLE
Parsing formulas in storm

### ISSUE THREAD

**Issue by mcubuktepe** [moves-rwth/storm#75]
Hi,

I had some troubles feeding multi-objective formulas in storm with this following minimal prism MDP [min_example.txt](https://github.com/moves-rwth/storm/files/4553066/min_example.txt):

Running the command "storm --prism min_example.txt --prop 'Pmax>=0.9 [F "target"]'  " gives the output

"Model checking property "1": Pmax>=9/10 [F "target"] ...
Result (for initial states): true

Time for model checking: 0.000s."
which is expected.

However, If I run the command "storm --prism min_example.txt --prop 'Pmin=? [Pmax>=0.9 [F "target"]]' ", I get the following output:

Time for model input parsing: 0.001s.

"WARN (cli.cpp:259): The model checking query does not seem to be supported for the selected engine. Storm will try to solve the query, but you will most likely get an error for at least one of the provided properties.
Time for model construction: 0.018s.

-------------------------------------------------------------- 
Model type: 	MDP (sparse)
States: 	36
Transitions: 	141
Choices: 	141
Reward Models:  none
State Labels: 	3 labels
   * deadlock -> 0 item(s)
   * target -> 1 item(s)
   * init -> 1 item(s)
Choice Labels: 	none
-------------------------------------------------------------- 

Model checking property "1": Pmin=? [Pmax>=9/10 [F "target"]] ...
ERROR (model-handling.h:847): Property is unsupported by selected engine/settings."

It looks like this property should be supported by storm, but I got this error. I think that I am making a parsing error for specifying multi-objective properties, but I wanted to open an issue to make sure.

Thanks a lot!

**Comment by volkm** [comment]
Hi Murat,

@tquatmann is the expert on multi-objective model checking, but let me try to help.
If you want to encode multi-objective properties you have to define them using the keyword `multi`. You can find an example and some documentation on the [Storm website](https://www.stormchecker.org/documentation/usage/running-storm.html#multi-objective-model-checking-of-mdps-and-markov-automata).

I hope that helps.
Matthias

**Comment by mcubuktepe** [comment]
Hi Matthias,

Thanks for the reply, for this updated example 
[min_example.txt](https://github.com/moves-rwth/storm/files/4553257/min_example.txt) and the following command " storm --prism min_example.txt --prop 'multi(Pmax=? [ F "crash" ], P>=0.5 [ F "target" ])' ", I am getting the following output:

-------------------------------------------------------------- 
Model type: 	MDP (sparse)
States: 	36
Transitions: 	141
Choices: 	141
Reward Models:  none
State Labels: 	4 labels
   * init -> 1 item(s)
   * crash -> 1 item(s)
   * deadlock -> 0 item(s)
   * target -> 1 item(s)
Choice Labels: 	none
-------------------------------------------------------------- 

Model checking property "1": multi(Pmax=? [F "crash"], P>=1/2 [F "target"]) ...
Result (for initial states): false

Time for model checking: 0.001s.

The output is unexpected for me as I am trying to compute Pmax of a property, but storm returns a false answer for this property. Note that the property "Pmax>=1/2 [F "target"] " is true for this minimal example.

Thanks a lot!

**Comment by tquatmann** [comment]
Hi Murat,
Usually, `false` would indicate that there is no policy satisfying the objectives with a value threshold (in your case `P>=1/2 [F "target"]`).
Here, this was indeed a bug that I have just fixed. After pulling and compiling the latest `master`, you should  now get `1` as a result.

Thank you very much for the report (and for using Storm's multi-objective algorithms).
Feel free to reopen the issue or create a new one in case something doesn't work.
Best,
Tim
