### ISSUE TITLE
Improvements for file `storm-version.cpp`

### ISSUE THREAD

**Issue by tquatmann** [moves-rwth/storm#78]
I suggest two possible enhancements regarding the automatically generated version information within the file `storm/utility/storm-version.cpp` 

* Move it to an appropriate location within the `build` folder (probably just like `build/include/storm-config.h`).
* Create a separate library `storm-version-info` which shall not be linked with `libstorm` but with the cli libraries and the stormpy bindings. This is to avoid the costly linking step for `libstorm` after doing a commit.

Any objections?
I could do the necessary steps within storm if someone else does it for stormpy :)

**Comment by sjunges** [comment]
Yes that sounds good. I think we should still ensure that it is compiled as often as possible. Maybe it would be good if it is a dependency for storm-lib (but does not link against it?). That means that you cannot build storm-lib without rebuilding storm-info? 

I can take care of the stormpy part. Maybe do this in a branch and tell me, then we can push it as soon as it is also done in stormpy (might take a week on my side).

**Comment by tquatmann** [comment]
[I already took care of stormpy.](https://github.com/moves-rwth/stormpy/commit/0cb3f0cee85252276cdcdef319fb963dc445d55a)
Wasn't so bad after all, but I wouldn't mind if you have a quick look :)
