### ISSUE TITLE
make install fails on carl

### ISSUE THREAD

**Issue by xblahoud** [moves-rwth/storm#85]
After building Storm on PoP_OS 20.04, the install step failed.

```
sudo make install
```

returns
```
[  0%] Built target carl
[  1%] Built target cudd3
...
[100%] Built target test-pomdp-modelchecker
Install the project...
-- Install configuration: "RELEASE"
CMake Error at cmake_install.cmake:41 (file):
  file INSTALL cannot find
  "/PATH_TO_STORM/storm/build/resources/3rdparty/carl/lib/libcarl.14.20.so":
  No such file or directory.
```
It seems there is a typo in the name of the file. I had `libcarl.so.14.20` in my `/PATH_TO_STORM/storm/build/resources/3rdparty/carl/lib/`.

Simply making a copy of the file and flip the `so` with `14.20` worked.

**Comment by volkm** [comment]
Thanks for the info. The filename for .so files differs between macOS and Linux. Linux uses the version as suffix whereas macOS places it before the file ending. I created a case distinction to fix this issue.
