### ISSUE TITLE
Double negation not being recognized by PRISM parser

### ISSUE THREAD

**Issue by arthuraa** [moves-rwth/storm#89]
Consider the following PRISM DTMC:

```
dtmc

module m0
pc_0 : [0..1];
[step] (!!(pc_0=0)) -> (pc_0' = 0);
endmodule
```

Storm gives me a parse error when reading this file, even though it is accepted by PRISM.

**Comment by tquatmann** [comment]
Thanks for the report! The latest commit in the `master` branch should fix this issue.
