### ISSUE TITLE
'make install' failed

### ISSUE THREAD

**Issue by huypn12** [moves-rwth/storm#98]
System: Opensuse Tumbleweed
Gcc 10.2
Libboost 1.74

Reproduce:
```
mkdir build && cd build
cmake ..
make
sudo make install
```

![grafik](https://user-images.githubusercontent.com/2792821/100925234-05d48880-34e2-11eb-8176-314cdc2e2e43.png)

**Comment by tquatmann** [comment]
Have you installed carl manually, like [this](https://www.stormchecker.org/documentation/obtain-storm/dependencies.html#manually-installing-dependencies-optional)? or did you let our build script do that for you? Both options should work, we just need this information for easier debugging.
Can you send us the output of `cmake ..` ?

**Comment by GavinRens** [comment]
Hello,

I'm trying to install stormpy.
I know I need storm for it, and apparently, they should be based on the same version.
This morning I cloned storm and it was version 1.6.3. This afternoon I started over (struggling to get things to work). Then storm was cloned as version 1.6.4 (dev).
When I do
git clone https://github.com/moves-rwth/stormpy.git --branch 1.6.4
I get fatal: Remote branch 1.6.4 not found in upstream origin

Please advise what I should do. Thanks.

**Comment by volkm** [comment]
I created a separate issue [here](https://github.com/moves-rwth/stormpy/issues/21) to keep the thread focused on the original issue.
